# Generated by Django 4.1.1 on 2022-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starttarief", models.IntegerField(max_length=3)),
                ("per_kilometer", models.IntegerField(max_length=3)),
            ],
        ),
    ]
