# Generated by Django 4.1.1 on 2022-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_tarief_per_kilometer_alter_tarief_starttarief"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarief", name="per_kilometer", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="tarief", name="starttarief", field=models.FloatField(),
        ),
    ]
